pipeline {
    agent any
    options {
        ansiColor('xterm')
    }

    stages {
        stage('Clonar Repositório') {
            steps {
                git branch: 'main', url: 'https://github.com/brunnomarin/testes-e2e-ebac-shop.git'
            }
        }

        stage ('Instalar Dependências') {
            steps {
                bat 'npm install'
            }
        }
        
       stage ('Executar Testes') {
            steps {
                bat 'npm run cy:run'
            }
        }

    }

}